//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.30 at 12:14:13 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dkey.com/spring/soap/api/loan", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dkey.spring.soap.api.loan;
